# Generated by Django 4.0.5 on 2022-07-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('creador', models.CharField(max_length=50, verbose_name='Profesor')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagenes')),
            ],
        ),
    ]
