# Generated by Django 4.0.5 on 2022-07-08 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name': 'Cursos', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='creates',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='update',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Actualizacion'),
            preserve_default=False,
        ),
    ]
