# Generated by Django 4.0.5 on 2022-07-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_comentariopublico_usuarios_alter_cursos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cursos', verbose_name='Curso')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuarios', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
