# Generated by Django 4.0.5 on 2022-08-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_compras_user_alter_perfil_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='compras',
            options={'ordering': ['-created'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
